### ISSUE TITLE
Greasemonkey/Tampermonkey support

### ISSUE THREAD

**Issue by RayBB** [arkadiyt/zoom-redirector#1]
It would be nice to add support for greasemonkey/tampermonkey.
Love the idea of this but don't want to install yet another extension.

**Comment by arkadiyt** [comment]
Thanks for the request - going to copy/paste my response on the [hackernews comment](https://news.ycombinator.com/item?id=22660424):

The current implementation uses the WebExtension apis to perform an _internal_ redirect. When you navigate to a Zoom meeting, before the browser opens a connection or sends a single network packet, the extension rewrites the url to navigate to their web client.

On the other hand tampermonkey/greasemonkey are content scripts that get injected into loaded pages. An implementation here would look like: the user navigates to a Zoom meeting, they load the entire page, and then a script gets injected to perform a `window.location` redirect. This will be slower and depending on the timing of events you may even still get the Zoom file download prompt.

So I don't think tampermonkey/greasemonkey is a good fit here.

**Comment by miraries** [comment]
Valid points, but a tampermonkey script version does appear to work fine, if op insists.
https://gist.github.com/miraries/32dcd6581734137cee7e108a5e22790b
