### ISSUE TITLE
[Feature Request] Add option to enable/disable

### ISSUE THREAD

**Issue by UInt2048** [arkadiyt/zoom-redirector#11]
There may be exceptions where there's one meeting that one would rather actually go to the app instead of the web client.

**Comment by ahrenstein** [comment]
I agree. My example use case is when I join from a computer where I prefer the client, vs another computer where I'd rather not be prompted to install the client. The extension syncs on Chrome across both machines, so a quick toggle would be handy.

**Comment by arkadiyt** [comment]
I've added toggle functionality by clicking on the extension icon and submitted it to the Chrome webstore for review - it's in version 1.0.4 and should be available as soon as Google reviews/publishes the new version.

**Comment by arkadiyt** [comment]
This is published on the chrome webstore now

**Comment by ahrenstein** [comment]
Thanks for adding this feature.
