### ISSUE TITLE
zoom.us/meeting/ type links

### ISSUE THREAD

**Issue by UInt2048** [arkadiyt/zoom-redirector#12]
Some Zoom links are in the format `http://zoom.us/meeting/123456789` and this extension doesn't support them.

Reference: https://sju.teamdynamix.com/TDClient/1942/Portal/KB/ArticleDet?ID=29897

**Edit:** It has come to my attention that `/s/` type meetings are supported, but this issue incorrectly stated that it was not (from a review on Chrome Web Store)

**Comment by arkadiyt** [comment]
`/s/` meetings are supported. Can you provide any documentation on how to generate a `/meeting/` meeting using Zoom?

**Comment by UInt2048** [comment]
Yes, just search up "Zoom error 3003." In short:

> As I mentioned earlier, it is just a glitch. But in reality, it is not a glitch because when a host assigns a co-host to the meeting. A link to the meeting is actually created for the co-host not for other participants.
>
>Being the co-host of the meeting, they must share the new link with the rest of the participants. But with a lack of knowledge, they share the link that was created for them. That results in error 3003 which states “not meeting host”, as, quite right because the co-host isn’t the meeting host.

Reference: https://openskynews.com/zoom-error-code-3003/07346/

**Comment by arkadiyt** [comment]
That doesn't make any sense to me - when I make someone a cohost neither I nor the recipient receives a link. Can you share concrete reproduction steps?

**Comment by UInt2048** [comment]
Closing this issue but will reopen if anyone else has this problem again
