### ISSUE TITLE
Manual installation for Firefox

### ISSUE THREAD

**Issue by adrianlshaw** [arkadiyt/zoom-redirector#14]
Very nice add-on, thank you for making it. As others may also do, I prefer to vet the code of the addons I install. So I've tried manually to install manually this in Firefox.

I've taken this repository, zipped it, and renamed the extension from .zip to .xpi. Since Firefox needs extensions to be signed, I've also disabled `xpinstall.signatures.required` in Firefox. Firefox says it appears to be corrupt without specifying more detail. 

Has anyone had any success with this method or has an idea as to what I should fix?

**Comment by arkadiyt** [comment]
I would try installing the [web-ext](https://github.com/mozilla/web-ext) cli and running `web-ext build` against the extension

**Comment by adrianlshaw** [comment]
Thanks for the tip! I  got it to work. After running `npm install web-ext -g` and `web-ext build` I then tried to install the resulting zip file. It was still saying "corrupted" but I discovered [here](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/) that you need to add the following in the manifest.json:

```json
"browser_specific_settings": {
  "gecko": {
    "id": "myaddon@example.com",
    "strict_min_version": "42.0"
  }
}
```

I didn't read about why this is needed. Anyhow, just writing this here in case anyone else wants to do the same thing.

**Comment by arkadiyt** [comment]
Glad to hear - thanks Adrian!
