### ISSUE TITLE
Removed from Chrome Web Store

### ISSUE THREAD

**Issue by danielcarraligent** [arkadiyt/zoom-redirector#16]
Zoom Redirector recently got removed from the Chrome Web Store with the message "This extension violates the Chrome Web Store policy."

This extension is so useful; do we know why it was removed and if it can be made available again?

**Comment by arkadiyt** [comment]
Zoom issued a trademark violation against this extension and had Google take it down:
https://twitter.com/arkadiyt/status/1500141960065028098

I'll try to upload it under a new name

**Comment by arkadiyt** [comment]
This has been republished here: https://chrome.google.com/webstore/detail/xoom-redirector/ocabkmapohekeifbkoelpmppmfbcibna?hl=en&authuser=0

**Comment by mariduv** [comment]
The name "Zoom Redirector", which is always displayed on the web store alongside "Offered by: arkadiyt.com," would typically be considered a trademark fair use in the US (denotes compatibility, uses name and not logo, little chance of product confusion), but this report was sent automatically.  You might respond noting this, and offer to change the name to "Redirector for Zoom" if that would be acceptable to the trademark holder.  This postfix pattern seems to be more popular and may get fewer automatic trademark complaints.  And I figure you want to keep your metrics and prior installs.

Third-party use of a trademark for compatibility purposes at the beginning of an extension's name:  
https://chrome.google.com/webstore/detail/google-meet-attendance-li/appcnhiefcidclcdjeahgklghghihfok
https://chrome.google.com/webstore/detail/facebook-demetricator/dbkgglbefgkimiadfjmgnkjmaoahephg

And at the end:
https://chrome.google.com/webstore/detail/checker-plus-for-google-c/hkhggnncdpfibdhinjiegagmopldibha
https://chrome.google.com/webstore/detail/social-fixer-for-facebook/ifmhoabcaeehkljcfclfiieohkohdgbb

**Comment by arkadiyt** [comment]
I'll give that a try tonight, thanks for the feedback @merrilymeredith
