### ISSUE TITLE
Renamed version not working in Chrome?

### ISSUE THREAD

**Issue by natevw** [arkadiyt/zoom-redirector#17]
Had no trouble with the redirects until Google disabled the original (#16). But now with the new Xoom Redirector version 1.0.2 installed, it is not redirecting and I keep getting the Zoom\.pkg download and have to manually click a few steps to find back the web meeting again.

I do not see anything in the console related to the Xoom Redirector extension. I tried getting rid of any cookies/localStorage/IndexDB that Zoom might have been using to track that I [well, **they**…] had already downloaded the installer in case that made a difference. I even tried enabling the extension in Incognito mode and pasting in a Zoom link there but same behavior. And it never mattered before whether I had the native client installed or not anyway.

The new extension does show up in the "Full Access" list for my Zoom links, but I noticed the name of it is grey for some reason:

<img width="353" alt="uBlock Origin and Xoom Redirector both in Chrome extension list, however the former is displayed with a darker label than the latter" src="https://user-images.githubusercontent.com/265902/159335115-5d259fd0-642e-4de1-9b84-8a361afef85d.png">

It stays grey even if I pin it or allow it in incognito mode, nothing I've tried makes a difference or indicates why it is grey in the first place. Now I tried removing the extension and re-adding it, with no change to any of this.

Any ideas or other things to try troubleshoot?

**Update**: also enabled developer mode for extensions, turned "Collect Errors" on and still nothing. No errors show, there is no background page to inspect, no signs of life that the extension is doing anything at all except exist as an installed extension.

**Comment by natevw** [comment]
Aha! I found the `atetelman--chrome` branch which uses some new [declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/) regexes instead of the background script: https://github.com/arkadiyt/zoom-redirector/blob/5dbe5de/rules.json

Those simply don't appear to be working. Fwiw, the URLs in question were roughly:

* <https://zoom.us/integration/NNNNN?params=##+long+base64+looking+data+##> — the original link clicked
* <https://zoom.us/j/NNNNN?pwd=###&_x_zm_rtaid=abc.detc&_x_zm_rhtaid=nnn#success> — what the original link redirects to (and stays at with the new v3 manifest extension)

Meanwhile I loaded the `master` branch of this repo as an unpacked extension and that restored the previous functionality.

**Comment by arkadiyt** [comment]
Unfortunately google doesn't allow uploading v2 extensions anymore, so I have to use declarativeNetRequest.

But even the v2 / javascript version did not do any redirects for /integration, so that never would have worked. Can you describe the steps to reach such a url?

**Comment by natevw** [comment]
The `/integration/` link comes from the meeting invite itself (presumedly referring to a Zoom plugin integrated into a team chat workspace). But shouldn't at least the `/j/` be redirected regardless?

**Comment by arkadiyt** [comment]
/j/ does work for me, I'm using the v3 manifest and all my meetings are redirected

**Comment by natevw** [comment]
To be clear, even if I paste in a `/j/` URL like the one above (with a password, some sort of tracking/other parameters, and a `#success` fragment…) directly it does not get Xoom redirected either. Running a download of the Chrome branch here unpacked via developer tools … still nothing.

I also tried dropping all the params and going to just <https://zoom.us/j/NNNNNNNNNNNN> directly and the app store version *also* didn't work on my machine. Finally I tried disabling all other extensions, and going to just the /j/NNN with no parameters… still nothing. :-/

This was Chrome 99.0.4844.74 btw, and just retested with 99.0.4844.83.

Personally I'm just going to go back to a dev install of the main v2-style branch which is still working fine. Feel free to close if you think this is just an edge case on my machine, or maybe others can chime in if they run into this and can figure out any additional clues.

**Comment by arkadiyt** [comment]
Ah - it only acts on subdomains of zoom.us. Even without having a paid account / using their free tier all meetings I find are on a subdomain of zoom.us - could you describe how to create meetings on the top level domain?

**Comment by natevw** [comment]
> could you describe how to create meetings on the top level domain?

These links come from a Slack plugin that Zoom provides:

* https://explore.zoom.us/en/zoom-slack-integration/
* https://slack.com/help/articles/115004062463-Zoom-for-Slack
* https://applications.zoom.us/slack/api/slackIntegration

I am just an invitee and didn't set up the hosting account or the integration myself, so I don't know anything more about how it's been configured specifically in this case.

**Comment by arkadiyt** [comment]
Can you try the latest version of the atetelman--chrome branch locally and see if that fixes it for you?

**Comment by natevw** [comment]
> Can you try the latest version of the atetelman--chrome branch locally and see if that fixes it for you?

Yep, seems like 7bbfc3a did the trick, thanks!

**Comment by arkadiyt** [comment]
This is submitted to the app store and should be published soon under version 1.0.3
