### ISSUE TITLE
Feature request: handle subdomains and non-digit based IDs

### ISSUE THREAD

**Issue by rowan-m** [arkadiyt/zoom-redirector#2]
Looks like the regex just checks for digits at the moment. The ID in the path can contain arbitrary characters. Paid users can create a customised personal meeting ID. That *may* be with a `/my/` path though.

Organisations also seem to get a subdomain under `zoom.us`, so that should be captured and prepended.

Take this all with a pinch of salt though, I'm just going off links I've seen shared.

**Comment by arkadiyt** [comment]
Subdomains are handled correctly already - if the original url was `blah.zoom.us/j/<id>` it'll redirect to `blah.zoom.us/wc/<id>/join`. I don't have a paid zoom but I will search around and see if I can get someone to generate some links for me - thanks!

**Comment by ryjones** [comment]
Our paid links look like

https://zoom.us/my/hyperledger.community.3

For instance. I can change that whenever I want.

**Comment by arkadiyt** [comment]
It looks like it performs a redirect to `https://zoom.us/j/5184947650` - I could save an extra round trip by adding code to handle this but it will also work as is today
