### ISSUE TITLE
Does this add more load on the Zoom servers?

### ISSUE THREAD

**Issue by HenrikBengtsson** [arkadiyt/zoom-redirector#4]
Does this add more load on the Zoom servers? Are we better citizens if we stay on the Zoom client, given we have access to that? #covid-19

**Comment by arkadiyt** [comment]
It does not add any additional load on zoom.

**Comment by HenrikBengtsson** [comment]
Thxs for the prompt reply.  To clarify and rule out miscommunication; I'm not talking about the extension but what happens to an active Zoom session.  My train of thought is that the client might be P2P whereas when we use the browser the all communication goes via the Zoom servers?  Was your reply an answer to this?

**Comment by arkadiyt** [comment]
The client is not P2P.
