### ISSUE TITLE
No video / audio in Firefox

### ISSUE THREAD

**Issue by ghost** [arkadiyt/zoom-redirector#6]
Thank you so much for making this addon to work around this dark pattern!

Obviously this issue is not about your browser extension per se but rather about the Zoom web client as it doesn't appear to work in Firefox (apart from the text-based chat):

> Your browser does not support using the computer’s Audio device. To use Zoom, install the latest version of a standard browser, such as Chrome.

Since this extension is [available for Firefox](https://addons.mozilla.org/en-US/firefox/addon/zoom-redirector/), I am wondering whether there's something I am missing, like another work-around to enable video and audio?

**Comment by wbob** [comment]
if firefox is not asking for permission, there used to be a [fix](https://www.zoom.us/wc/support/mic) suggested in the websdk [changelog](https://github.com/zoom/websdk/blob/master/CHANGELOG.md) . It is not effective atm, audio somehow doesn't get past the initialization, video does.

**Comment by arkadiyt** [comment]
I don't know what the answer to this is but I don't think this is the place for it. I would recommend looking through the Zoom knowledge base or reaching out to their support - thanks

**Comment by ghost** [comment]
> I don't think this is the place for it.

Makes sense. :+1:

**Comment by wbob** [comment]
sorry for the minor issue spam: Audio in Firefox will start to work with FF76, as then the [AudioWorklets](https://bugzilla.mozilla.org/show_bug.cgi?id=1062849) will be implemented. You can check it out today with Nightly.
