### ISSUE TITLE
Zoom has disabled their web client

### ISSUE THREAD

**Issue by Vulpeculus** [arkadiyt/zoom-redirector#7]
The plugin does not work if a conference password has been set.

It results in a "403 Forbidden" error

**Comment by mtsknn** [comment]
This problem may not be related to this extension. See https://devforum.zoom.us/t/webinar-from-browser-403-forbidden/10782

The extension did work last night (about 15 hours ago) when I tried it, but now I get the "403 Forbidden" error as well when trying to join via the browser. I get the error even without the extension.

**Comment by arkadiyt** [comment]
This is unfortunately correct - Zoom has disabled their web client and is now requiring people to use their desktop client. They posted the following on their [status page](https://status.zoom.us/):

> **Resolved** - Zoom will be placing the Web Client into maintenance mode and take this part of the service offline. This will also impact users utilizing Zoom’s Web SDK. This will have no impact on users utilizing Zoom’s desktop or mobile application.
>
> We apologize for any inconvenience that this may cause.

**Comment by Wolf480pl** [comment]
Looks like that "resolved" thing was a confusion, and they do intend to get the web client back online:

> We are working to get the Zoom Web Client 1 and Zoom Web SDK 3 back online.

https://devforum.zoom.us/t/in-progress-webinar-from-browser-403-forbidden/10782/40

and

> [...] we are hard at work bringing up these services. It is a top priority for us.

https://devforum.zoom.us/t/in-progress-webinar-from-browser-403-forbidden/10782/58

**Comment by kevinl95** [comment]
The web client is back, but they are now forcing everyone using it to sign in with a Zoom account.

**Comment by arkadiyt** [comment]
I can only presume they think this will reduce wardialing, even though the Zoom desktop client does allow joining meetings without being signed in, and hence people can use that API instead.

In any case, closing this issue as it is now resolved.
