### ISSUE TITLE
Safari Extensions

### ISSUE THREAD

**Issue by cgarrovillo** [arkadiyt/zoom-redirector#8]
Are there any plans for a Safari extension? Would love to see one considering Zoom's extensive vulnerabilities & privacy issues on MacOS

**Comment by arkadiyt** [comment]
Hey @cgarrovillo, no plans for a Safari extension at this time because they don't support the WebExtension API - I'd have to write an addon from scratch for them, whereas Chrome/Firefox/Edge/Opera all run off this single codebase

**Comment by blue-stalfos** [comment]
You may not have to rewrite it from scratch: https://developer.apple.com/news/?id=kuswih5l

**Comment by arkadiyt** [comment]
Their WebExtension implementation won't allow this extension to function. In particular on [this compatibility page](https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility
) they note:
```
webRequest
    BlockingResponse not supported.
    Blocking requests not supported.
    opt_extraInfoSpec not supported for any of the events.
```
These are required for zoom-redirector to work.
